name: food_delivery
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+2
  form_validator: ">=0.1.1 <2.0.0"
  device_info: ^0.4.0+4
  logger: ^0.7.0+2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  splashscreen: ^1.3.5
  flutter_udid: ^2.0.0
  retrofit: ^1.3.4+1
  build_runner: ^1.12.2
  fluttertoast: ^3.1.0
  loading_overlay: ^0.3.0
  flutter_screenutil: ^5.0.0
  shared_preferences: ^2.0.5
  google_maps_flutter: ^0.5.21
  location: ^3.0.2
  geolocator: ^6.2.1
  geocoding: ^1.0.5
  permission_handler: ^5.1.0+2
  geocoder: ^0.2.1
  floor: any



dev_dependencies:
  flutter_test:
    sdk: flutter
  floor_generator: any



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Proxima_Nova_Alt_Bold
      fonts:
        - asset: assets/fonts/proxima_bold/Proxima Nova Alt Bold.otf

    - family: Proxima_Nova_Alt_Condensed_Bold
      fonts:
        - asset: assets/fonts/proxima_bold/Proxima Nova Alt Condensed Bold.otf

    - family: Proxima_Nova_Alt_Extra_Condensed_Bold
      fonts:
        - asset: assets/fonts/proxima_bold/Proxima Nova Alt Extra Condensed Bold.otf

    - family: Proxima_Nova_Condensed_Bold
      fonts:
        - asset: assets/fonts/proxima_bold/Proxima Nova Condensed Bold.otf

    - family: Proxima_Nova_Extra_Condensed_Bold
      fonts:
        - asset: assets/fonts/proxima_bold/Proxima Nova Extra Condensed Bold.otf

    - family: Proxima_Nova_ScOsf_Bold
      fonts:
        - asset: assets/fonts/proxima_bold/Proxima Nova ScOsf Bold.otf


    - family: Proxima_Nova_ScOsf_Condensed_Bold
      fonts:
        - asset: assets/fonts/proxima_bold/Proxima Nova ScOsf Condensed Bold.otf

    - family: Proxima_Nova_ScOsf_Extra_Condensed_Bold
      fonts:
        - asset: assets/fonts/proxima_bold/Proxima Nova ScOsf Extra Condensed Bold.otf

    #LIGHT FONT STYLE

    - family: Proxima_Nova_Alt_Condensed_Light
      fonts:
        - asset: assets/fonts/proxima_light/Proxima Nova Alt Condensed Light.otf

    - family: Proxima_Nova_Alt_Extra_Condensed_Light
      fonts:
        - asset: assets/fonts/proxima_light/Proxima Nova Alt Extra Condensed Light.otf

    - family: Proxima_Nova_Alt_Light
      fonts:
        - asset: assets/fonts/proxima_light/Proxima Nova Alt Light.otf

    - family: Proxima_Nova_Extra_Condensed_Light
      fonts:
        - asset: assets/fonts/proxima_light/Proxima Nova Extra Condensed Light.otf

    - family: Proxima_Nova_ScOsf_Extra_Condensed_Light
      fonts:
        - asset: assets/fonts/proxima_light/Proxima Nova ScOsf Extra Condensed Light.otf

    - family: Proxima_Nova_ScOsf_Light
      fonts:
        - asset: assets/fonts/proxima_light/Proxima Nova ScOsf Light.otf


    # REQULAR FONT STYLE

    - family: Proxima_Nova_Alt_Regular
      fonts:
        - asset: assets/fonts/proxima_reg/Proxima Nova Alt Regular.otf

    - family: ProximaNova_Regular
      fonts:
        - asset: assets/fonts/proxima_reg/ProximaNova-Regular.otf

    # Thin FONT STYLE

    - family: Proxima_Nova_Alt_Condensed_Thin
      fonts:
        - asset: assets/fonts/proxima_thin/Proxima Nova Alt Condensed Thin.otf

    - family: Proxima_Nova_Alt_Extra_Condensed_Thin
      fonts:
        - asset: assets/fonts/proxima_thin/Proxima Nova Alt Extra Condensed Thin.otf

    - family: Proxima_Nova_Alt_Thin.otf
      fonts:
        - asset: assets/fonts/proxima_thin/Proxima Nova Alt Thin.otf

    - family: Proxima_Nova_Condensed_Thin
      fonts:
        - asset: assets/fonts/proxima_thin/Proxima Nova Condensed Thin.otf

    - family: Proxima_Nova_Extra_Condensed_Thin
      fonts:
          - asset: assets/fonts/proxima_thin/Proxima Nova Extra Condensed Thin.otf

    - family: Proxima_Nova_ScOsf_Condensed_Thin
      fonts:
        - asset: assets/fonts/proxima_thin/Proxima Nova ScOsf Condensed Thin.otf

    - family: Proxima_Nova_ScOsf_Extra_Condensed_Thin
      fonts:
        - asset: assets/fonts/proxima_thin/Proxima Nova ScOsf Extra Condensed Thin.otf

    - family: Proxima_Nova_ScOsf_Thin
      fonts:
        - asset: assets/fonts/proxima_thin/Proxima Nova ScOsf Thin.otf

    - family: Proxima_Nova_Thin
      fonts:
        - asset: assets/fonts/proxima_thin/Proxima Nova Thin.otf



          # - asset: fonts/Schyler-Italic.ttf
    #   style: italic
      #- family: Trajan Pro
      #fonts:
      # - asset: fonts/TrajanPro.ttf
      #   - asset: fonts/TrajanPro_Bold.ttf
    #     weight: 700


  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
